### ISSUE TITLE
NativeModules.DevSettings is an empty object

### ISSUE THREAD

**Issue by Sowed** [gusgard/react-native-devsettings#1]
Hi @gusgard. Thank you for this approach.

However, I am having an issue running this package in a React Native version `0.71.7` app.  I get the following error...
> TypeError: Cannot read property 'setIsDebuggingRemotely' of null
TypeError: Cannot read property 'setIsDebuggingRemotely' of null

Triggered by `NativeModules.DevSettings.setIsDebuggingRemotely(isDebuggingRemotely);`.
https://github.com/gusgard/react-native-devsettings/blob/822cb8fdb28198fc73ae18ace33e540f81b50ee5/index.ts#L18

On logging `NativeModules`, it turns out to be an empty object.
Patched it to `NativeModules.DevSettings?.setIsDebuggingRemotely(isDebuggingRemotely);` to prevent the breaking error but the debugger is still not working. Any idea how I can go about this?

Came from [react-native-debugger/issues/573](https://github.com/jhen0409/react-native-debugger/issues/573)

**Comment by gusgard** [comment]
Hey, I'm not really sure because we are in `0.71.7` and it is working correctly.  Is this happening on both platforms iOS and Android? Could you share your `Podfile.lock` and `package.json`?  

I wonder if you could try with something like `setTimeout(() => require('react-native-devsettings'), 3 * 1000);` (might be helpful if you are loading a lot of packages)

**Comment by Sowed** [comment]
This approach did not work. I even tried loading the source code directly into my code and added the timeout there. Still no luck.

Here the pod file

```ruby
pod_folder = Pathname.new(__FILE__).dirname.realpath

require File.join(File.dirname(`cd #{pod_folder} && node --print "require.resolve('expo/package.json')"`), "scripts/autolinking")
require File.join(File.dirname(`cd #{pod_folder} && node --print "require.resolve('react-native/package.json')"`), "scripts/react_native_pods")
require File.join(File.dirname(`cd #{pod_folder} && node --print "require.resolve('@react-native-community/cli-platform-ios/package.json')"`), "native_modules")

# Minimum 13.0 for Expo 47
platform :ios, "13.0"
prepare_react_native_project!

production = ENV["PRODUCTION"] == "1"

# If you are using a `react-native-flipper` your iOS build will fail when `NO_FLIPPER=1` is set.
# because `react-native-flipper` depends on (FlipperKit,...) that will be excluded
#
# To fix this you can also exclude `react-native-flipper` using a `react-native.config.js`
# ```js
# module.exports = {
#   dependencies: {
#     ...(process.env.NO_FLIPPER ? { 'react-native-flipper': { platforms: { ios: null } } } : {}),
# ```
flipper_config = ENV['NO_FLIPPER'] == "1" ? FlipperConfiguration.disabled : FlipperConfiguration.enabled
linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

target 'MyApp' do
  use_expo_modules!
  post_integrate do |installer|
    begin
      expo_patch_react_imports!(installer)
    rescue => e
      Pod::UI.warn e
    end
  end
  config = use_native_modules!

  # Flags change depending on the env values.
  flags = get_default_flags()

  use_react_native!(
    :path => config[:reactNativePath],
    :production => production,
    # Hermes is now enabled by default. Disable by setting this flag to false.
    # Upcoming versions of React Native may rely on get_default_flags(), but
    # we make it explicit here to aid in the React Native upgrade process.
    :hermes_enabled => flags[:hermes_enabled],
    :fabric_enabled => flags[:fabric_enabled],
    # Enables Flipper.
    #
    # Note that if you have use_frameworks! enabled, Flipper will not work and
    # you should disable the next line.
    :flipper_configuration => flipper_config,
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  target 'MyAppTests' do
    inherit! :complete
    # Pods for testing
  end

  post_install do |installer|
    react_native_post_install(installer,
      # Set `mac_catalyst_enabled` to `true` in order to apply patches
      # necessary for Mac Catalyst builds
      :mac_catalyst_enabled => false
    )

    # Fix ios version errors in pods, like ReactCodeGen using 11.0 to use 13.0
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['SWIFT_VERSION'] = '5.0'
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
      end
    end

    __apply_Xcode_12_5_M1_post_install_workaround(installer)
    File.delete("./.xcode.env.local") if File.exist?("./.xcode.env.local")
  end
end

```

**Comment by gusgard** [comment]
> This approach did not work. I even tried loading the source code directly into my code and added the timeout there. Still no luck.
> 
> Here the pod file
> 
> ...
> 

Could you share your Podfile.lock file? Are you having the same issue on Android ?

**Comment by luisfuertes** [comment]
Try to install [react-native-async-storage](https://react-native-async-storage.github.io/async-storage/docs/install/) if you don't have it installed. It isnt in README but it is necessary to install it for this library to work

(Or is it necessary do pod install after npm install this library)

**Comment by gusgard** [comment]
Updated the package to don't require `react-native-async-storage`, it will work well with `import "react-native-devsettings";` but if you have `AsyncStorage` please use `import "react-native-devsettings/withAsyncStorage";`
