### ISSUE TITLE
Any guidance for using this in an Expo app?

### ISSUE THREAD

**Issue by jncampbell** [gusgard/react-native-devsettings#2]
This works perfectly in my react native app but I'm having trouble getting this to work in very basic Expo v48.0.15 application. 

Steps to reproduce:
1. npx create-expo-app --template
2. Choose `Navigation (TypeScript)` from list of templates
3. cd `app-name`
4. run `yarn add react-native-devsettings`
5. Add `import react-native-devsettings` to top of root `index.ts` file
6. Open React Native Debugger -> Press `CMD-T` to open port config menu  -> Update port to 19000
7. Start expo app with `yarn expo start` from project root
8. Wait for menu screen and select `i` to open iOS simulator
9. When simulator is booted, open dev menu and select "Open JS Debugger"

This will open the debugger in the default browser.

**Comment by gusgard** [comment]
Unfortunately, `expo` don't export `NativeModules.DevSettings` so this package only works with React Native and Expo Bare.
