### ISSUE TITLE
Requiring unknown module "undefined".

### ISSUE THREAD

**Issue by aravi365** [gusgard/react-native-devsettings#3]
Getting the error
`Requiring unknown module "undefined". If you are sure the module exists, try restarting Metro. You may also want to run `yarn` or `npm install`.`

When importing `import 'react-native-devsettings'; `on App.js
![Screenshot 2023-05-31 at 1 29 46 PM](https://github.com/gusgard/react-native-devsettings/assets/15327129/d08459c5-a04a-42f6-a532-0193c88adc87)

**Comment by bsspencer42** [comment]
Seeing the same issue on 0.71.6

**Comment by gusgard** [comment]
Fixed in 1.0.5

Related to https://github.com/gusgard/react-native-devsettings/issues/1#issuecomment-1581029208
