### ISSUE TITLE
react-native-reanimated not working when debugging JS

### ISSUE THREAD

**Issue by weiss-dhc** [gusgard/react-native-devsettings#4]
Like the title says. Just accidentally found out why my animation does not work because I forgot to enable the debugger. 

But I guess it is in the nature of this thing somehow getting around Hermes or so? Because react-native-reanimated depends on Hermes Engine.

Any idea how I can use both?

**Comment by gusgard** [comment]
I'm expecting that this package won't be needed once react-native-debugger v15 is released 🙏 

For now, just wait for the new version of `react-native-debugger`

https://github.com/jhen0409/react-native-debugger/discussions/774
