### ISSUE TITLE
Is this guaranteed not to have any impact on a production build?

### ISSUE THREAD

**Issue by JeremyBradshaw7** [gusgard/react-native-devsettings#6]
This works, as otherwise I cannot seem to debug in chrome when hermes is on using RN0.70, though I've followed the [guideiines](https://reactnative.dev/docs/0.70/hermes#debugging-js-on-hermes-using-google-chromes-devtools).

But is this guaranteed not to have any impact on a production build, or do I have to take steps to bypass the code changes from my master repo?

Should the package install go in the dependencies or devDependencies section of package.json?

**Comment by gusgard** [comment]
The code is executed when you are in develop mode https://github.com/gusgard/react-native-devsettings/blob/366cb7bddfc635655726f5866f3766c7ff7374ee/index.ts#L18
