### ISSUE TITLE
 No permission handler detected

### ISSUE THREAD

**Issue by hoangtrunnam** [gusgard/react-native-devsettings#7]
I can not debug :(. please help me. I tried to rebuild it. but it does not work
 
 No permission handler detected.

• Check that you are correctly calling setup_permissions in your Podfile.
• Uninstall this app, reinstall your Pods, delete your Xcode DerivedData folder and rebuild it.

![simulator_screenshot_13626BCD-F4E6-489C-8ED3-8C70C9B5BF2B](https://github.com/gusgard/react-native-devsettings/assets/57910461/b8f96507-01d1-4e7a-b9e7-92b55c5e8f41)
<img width="1293" alt="Screenshot 2023-11-10 at 13 17 54" src="https://github.com/gusgard/react-native-devsettings/assets/57910461/add883ed-4035-4989-a139-932bd259cada">
<img width="1293" alt="Screenshot 2023-11-10 at 13 18 03" src="https://github.com/gusgard/react-native-devsettings/assets/57910461/c659d7ef-6abf-434c-8ce8-e286f32eb976">

**Comment by hoangtrunnam** [comment]
"react-native": "0.72.5",
react native debugger: lastest ver: 0.14.0

**Comment by hoangtrunnam** [comment]
this is my pod file: 
![code4](https://github.com/gusgard/react-native-devsettings/assets/57910461/61f29f63-3edf-420b-a858-0fd7ad7f2b97)

**Comment by gusgard** [comment]
This is a tiny package if it doesn't work I recommend you to create a new project on React Native and check if your setup is correct
